[workspace]
authors = ["LeStoe11 <lennart@stoepler.de>"]
channels = ["conda-forge"]
name = "last_env"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
_libgcc_mutex = { version = "==0.1", build = "conda_forge" }
_openmp_mutex = { version = "==4.5", build = "2_gnu" }
bzip2 = { version = "==1.0.8", build = "h4bc722e_7" }
ca-certificates = { version = "==2025.8.3", build = "hbd8a1cb_0" }
ld_impl_linux-64 = { version = "==2.44", build = "h1423503_1" }
libexpat = { version = "==2.7.1", build = "hecca717_0" }
libffi = { version = "==3.4.6", build = "h2dba641_1" }
libgcc = { version = "==15.1.0", build = "h767d61c_4" }
libgcc-ng = { version = "==15.1.0", build = "h69a702a_4" }
libgomp = { version = "==15.1.0", build = "h767d61c_4" }
liblzma = { version = "==5.8.1", build = "hb9d3cd8_2" }
libnsl = { version = "==2.0.1", build = "hb9d3cd8_1" }
libsqlite = { version = "==3.50.4", build = "h0c1763c_0" }
libuuid = { version = "==2.38.1", build = "h0b41bf4_0" }
libxcrypt = { version = "==4.4.36", build = "hd590300_1" }
libzlib = { version = "==1.3.1", build = "hb9d3cd8_2" }
ncurses = { version = "==6.5", build = "h2d0b736_3" }
openssl = { version = "==3.5.2", build = "h26f9b46_0" }
pip = { version = "==25.2", build = "pyh8b19718_0" }
python = { version = "==3.10.18", build = "hd6af730_0_cpython" }
readline = { version = "==8.2", build = "h8c095d6_2" }
setuptools = { version = "==80.9.0", build = "pyhff2d567_0" }
tk = { version = "==8.6.13", build = "noxft_hd72426e_102" }
tzdata = { version = "==2025b", build = "h78e105d_0" }
wheel = { version = "==0.45.1", build = "pyhd8ed1ab_1" }
nodejs = "*"
yarn = "*"

[pypi-dependencies]
accelerate = "==1.10.0"
aiohappyeyeballs = "==2.6.1"
aiohttp = "==3.12.15"
aiosignal = "==1.4.0"
altair = "==5.5.0"
annotated-types = "==0.7.0"
antlr4-python3-runtime = "==4.8"
anyio = "==4.10.0"
async-timeout = "==5.0.1"
attrs = "==25.3.0"
av = "==14.2.0"
blessed = "==1.21.0"
blinker = "==1.9.0"
boto3 = "==1.40.12"
botocore = "==1.40.12"
cachetools = "==6.1.0"
certifi = "==2025.8.3"
charset-normalizer = "==3.4.3"
click = "==8.2.1"
cmake = "==4.1.0"
cycler = "==0.12.1"
datasets = "==1.18.3"
dill = "==0.4.0"
distro = "==1.9.0"
einops = "==0.4.0"
elasticsearch = "==7.15.2"
exceptiongroup = "==1.3.0"
fairscale = "==0.4.13"
filelock = "==3.19.1"
flask = "==3.1.1"
flask-cors = "==6.0.1"
fonttools = "==4.59.1"
frozenlist = "==1.7.0"
fsspec = "==2025.7.0"
git-python = "==1.0.3"
gitdb = "==4.0.12"
gitpython = "==3.1.45"
gpustat = "==1.1"
h11 = "==0.16.0"
hf-xet = "==1.1.8"
higher = "==0.2.1"
httpcore = "==1.0.9"
httpx = "==0.28.1"
huggingface-hub = "==0.34.4"
hydra-core = "==1.1.1"
idna = "==3.10"
importlib-metadata = "==6.3.0"
iopath = "==0.1.10"
itsdangerous = "==2.2.0"
jinja2 = "==3.1.6"
jiter = "==0.10.0"
jmespath = "==1.0.1"
joblib = "==1.5.1"
jsonnet = "==0.21.0"
jsonschema = "==4.25.1"
jsonschema-specifications = "==2025.4.1"
kiwisolver = "==1.4.9"
lit = "==18.1.8"
markupsafe = "==3.0.2"
matplotlib = "==3.5.1"
mpmath = "==1.3.0"
multidict = "==6.6.4"
multiprocess = "==0.70.18"
narwhals = "==2.1.2"
networkx = "==3.4.2"
nltk = "==3.6.5"
numpy = "==1.23.5"
nvidia-cublas-cu11 = "==11.10.3.66"
nvidia-cublas-cu12 = "==12.1.3.1"
nvidia-cuda-cupti-cu11 = "==11.7.101"
nvidia-cuda-cupti-cu12 = "==12.1.105"
nvidia-cuda-nvrtc-cu11 = "==11.7.99"
nvidia-cuda-nvrtc-cu12 = "==12.1.105"
nvidia-cuda-runtime-cu11 = "==11.7.99"
nvidia-cuda-runtime-cu12 = "==12.1.105"
nvidia-cudnn-cu11 = "==8.5.0.96"
nvidia-cudnn-cu12 = "==9.1.0.70"
nvidia-cufft-cu11 = "==10.9.0.58"
nvidia-cufft-cu12 = "==11.0.2.54"
nvidia-cufile-cu12 = "==1.13.1.3"
nvidia-curand-cu11 = "==10.2.10.91"
nvidia-curand-cu12 = "==10.3.2.106"
nvidia-cusolver-cu11 = "==11.4.0.1"
nvidia-cusolver-cu12 = "==11.4.5.107"
nvidia-cusparse-cu11 = "==11.7.4.91"
nvidia-cusparse-cu12 = "==12.1.0.106"
nvidia-cusparselt-cu12 = "==0.7.1"
nvidia-ml-py = "==13.580.65"
nvidia-nccl-cu11 = "==2.14.3"
nvidia-nccl-cu12 = "==2.20.5"
nvidia-nvjitlink-cu12 = "==12.8.93"
nvidia-nvtx-cu11 = "==11.7.91"
nvidia-nvtx-cu12 = "==12.1.105"
omegaconf = "==2.1.1"
openai = "==1.57.0"
opencv-python = "==4.8.0.76"
packaging = "==25.0"
pandas = "==1.4.0"
peft = "==0.7.1"
pickle5 = "==0.0.11"
pillow = "==11.3.0"
portalocker = "==3.2.0"
propcache = "==0.3.2"
protobuf = "==6.32.0"
psutil = "==7.0.0"
pyarrow = "==20.0.0"
pydantic = "==2.11.7"
pydantic-core = "==2.33.2"
pydeck = "==0.9.1"
pyhocon = "==0.3.61"
pyjwt = "==2.8.0"
pyparsing = "==3.2.3"
python-dateutil = "==2.9.0.post0"
pytz = "==2025.2"
pyyaml = "==6.0"
qwen-vl-utils = "==0.0.10"
referencing = "==0.36.2"
regex = "==2025.7.34"
requests = "==2.32.5"
requests-aws4auth = "==1.3.1"
rouge = "==1.0.1"
rpds-py = "==0.27.0"
s3transfer = "==0.13.1"
safetensors = "==0.6.2"
scikit-learn = "==1.0.2"
scipy = "==1.15.3"
sentence-transformers = "==3.2.1"
sentencepiece = "==0.2.0"
six = "==1.17.0"
smmap = "==5.0.2"
sniffio = "==1.3.1"
streamlit = "==1.48.1"
sympy = "==1.14.0"
tenacity = "==9.1.2"
threadpoolctl = "==3.6.0"
timm = "==0.9.7"
tokenizers = "==0.20.3"
toml = "==0.10.2"
torch = "==2.4.0"
torchvision = "*"
tornado = "==6.5.2"
tqdm = "==4.62.3"
transformers = "==4.46.2"
triton = "==3.0.0"
typing-extensions = "==4.14.1"
typing-inspection = "==0.4.1"
urllib3 = "==1.26.20"
watchdog = "==6.0.0"
wcwidth = "==0.2.13"
werkzeug = "==3.1.3"
wordcloud = "==1.9.4"
xxhash = "==3.5.0"
yarl = "==1.20.1"
zhipuai = "==2.1.5.20250415"
zipp = "==3.23.0"
